# Generated by Django 2.0.5 on 2018-05-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_retrieval', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(default='none', upload_to=''),
            preserve_default=False,
        ),
    ]
