# Generated by Django 2.0.5 on 2018-05-13 00:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info_retrieval', '0003_auto_20180513_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default='nada', upload_to='DOCS/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='text',
            field=models.TextField(default='nada'),
            preserve_default=False,
        ),
    ]
