# Generated by Django 2.0.5 on 2018-05-13 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_retrieval', '0004_auto_20180513_0026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
