# Generated by Django 2.0.5 on 2018-05-13 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_retrieval', '0005_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='document',
            name='text',
        ),
    ]
