# Generated by Django 2.0.5 on 2018-05-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_retrieval', '0006_auto_20180513_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.TextField(default='nada', verbose_name='null'),
            preserve_default=False,
        ),
    ]
