# Generated by Django 2.0.5 on 2018-05-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_retrieval', '0007_document_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.Field(verbose_name='null'),
        ),
    ]
