# Generated by Django 2.0.5 on 2018-05-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_retrieval', '0009_remove_document_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='naaaada', max_length=100),
            preserve_default=False,
        ),
    ]
