# Generated by Django 2.0.5 on 2018-05-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_retrieval', '0010_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.CharField(default='sds', max_length=10),
            preserve_default=False,
        ),
    ]
